<?php

/**
 * This is the model base class for the table "{{position}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Position".
 *
 * Columns in table "{{position}}" available as properties of the model,
 * followed by relations of table "{{position}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $station_id
 * @property integer $date
 * @property double $lat
 * @property double $lng
 *
 * @property Station $station
 */
abstract class BasePosition extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{position}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Position|Positions', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('date, lat, lng', 'required'),
			array('id, station_id, date', 'numerical', 'integerOnly'=>true),
			array('lat, lng', 'numerical'),
			array('id, station_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, station_id, date, lat, lng', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'station' => array(self::BELONGS_TO, 'Station', 'station_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'station_id' => null,
			'date' => Yii::t('app', 'Date'),
			'lat' => Yii::t('app', 'Lat'),
			'lng' => Yii::t('app', 'Lng'),
			'station' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('station_id', $this->station_id);
		$criteria->compare('date', $this->date);
		$criteria->compare('lat', $this->lat);
		$criteria->compare('lng', $this->lng);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}