<?php

/**
 * This is the model base class for the table "{{user}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "User".
 *
 * Columns in table "{{user}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property string $email
 * @property string $password
 * @property string $username
 * @property string $role
 * @property integer $lastLogin
 *
 */
abstract class BaseUser extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{user}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'User|Users', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, email, password, username', 'required'),
			array('lastLogin', 'numerical', 'integerOnly'=>true),
			array('name, email', 'length', 'max'=>64),
			array('password', 'length', 'max'=>128),
			array('username', 'length', 'max'=>32),
			array('role', 'length', 'max'=>16),
			array('role, lastLogin', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, email, password, username, role, lastLogin', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'email' => Yii::t('app', 'Email'),
			'password' => Yii::t('app', 'Password'),
			'username' => Yii::t('app', 'Username'),
			'role' => Yii::t('app', 'Role'),
			'lastLogin' => Yii::t('app', 'Last Login'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('password', $this->password, true);
		$criteria->compare('username', $this->username, true);
		$criteria->compare('role', $this->role, true);
		$criteria->compare('lastLogin', $this->lastLogin);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}