<?php

/**
 * This is the model base class for the table "{{station}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Station".
 *
 * Columns in table "{{station}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property string $token
 * @property string $phone
 *
 */
abstract class BaseStation extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{station}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Station|Stations', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('id, name, token', 'required'),
			array('id', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>64),
			array('token', 'length', 'max'=>32),
			array('phone', 'length', 'max'=>16),
			array('phone', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, token, phone', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'token' => Yii::t('app', 'Token'),
			'phone' => Yii::t('app', 'Phone'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('token', $this->token, true);
		$criteria->compare('phone', $this->phone, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}