<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-12 at 12:21:32.
 */
class GraphsApiControllerTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var GraphsApiController
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new GraphsApiController("graphsApiController");
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers GraphsApiController::init
	 * @todo   Implement testInit().
	 */
	public function testInit() {
		$this->assertInstanceOf("WebUser", Yii::app()->user);
		Yii::app()->user->setState("selected-station", 999);
		Yii::app()->user->setState("selected-interval", "daily");
		Yii::app()->user->setState("selected-time", 1396418760);
		
		// Remove the following lines when you implement this test.
		/*$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);*/
	}

	/**
	 * @covers GraphsApiController::actionGetseries
	 * @todo   Implement testActionGetseries().
	 */
	public function testActionGetseries() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
	
	/**
	 * @covers GraphsApiController::getseries
	 * @todo   Implement testActionGetseries().
	 */
	public function testGetSeries() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers GraphsApiController::getSeriesData
	 * @todo   Implement testGetSeriesData().
	 */
	public function testGetSeriesData() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers GraphsApiController::dateOf
	 * @todo   Implement testDateOf().
	 */
	public function testDateOf() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers GraphsApiController::setSubtitle
	 * @todo   Implement testSetSubtitle().
	 */
	public function testSetSubtitle() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}
