<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-11 at 19:45:06.
 */
class StationApiControllerTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var StationApiController
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new StationApiController("id");
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers StationApiController::actionIndex
	 * @todo   Implement testActionIndex().
	 */
	public function testActionIndex() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers StationApiController::actionUploadFile
	 * @todo   Implement testActionUploadFile().
	 */
	public function testActionUploadFile() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers StationApiController::actionTellPosition
	 * @todo   Implement testActionTellPosition().
	 */
	public function testActionTellPosition() {
		$token = "asdf";
		$result = $this->object->tellPosition(32.23543, 12.423445, 999, $token);
		$this->assertTrue($result);
	}

}
