<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-11 at 19:45:06.
 */
class StationApiControllerTest extends PHPUnit_Framework_TestCase {

	protected $stationid = 1;
	protected $token = "0aca0985c3b0a45c096565abd4994791";
	
	/**
	 * @var StationApiController
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new StationApiController("id");
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}


	/**
	 * @group Integration
	 * @covers StationApiController::actionUploadFile
	 * @todo   Implement testActionUploadFile().
	 */
	public function testActionUploadFile() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
	
	/**
	 * @group Unit
	 * @covers StationApiController::requestNewStation
	 */
	public function testRequestNewStation() {
		$station = $this->object->requestNewStation();
		$this->assertInstanceOf('Station', $station);
		if ($station)
			$station->delete();
	}

	/**
	 * @group Unit
	 * @covers StationApiController::tellPosition
	 */
	public function testTellPosition() {
		$answer;
		$result = $this->object->tellPosition($this->stationid, 32.23543, 12.423445, $this->token, $answer);
		$this->assertTrue($result);
		if ($result) {
			$posid = Yii::app()->db->getLastInsertID();
			Position::model()->deleteByPk($posid);
		}
	}
}
