<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-12 at 09:28:19.
 */
class DataUploaderTest extends PHPUnit_Framework_TestCase {

	protected $data = " V1;1396418762;153300.58;10.06;60.22
						V1;1396418822;153300.58;10.09;59.60
						V1;1396418882;5330.58;10.13;59.96
						V1;1396418942;15330.58;10.19;59.66
						V1;1396419002;1533.58;10.23;59.41
						V1;1396419063;1533.58;10.25;58.67
						V1;1396419122;1533.58;10.28;60.08
						V1;1396419182;153.58;10.30;59.09
						V1;1396419242;153.58;10.30;59.32
						V1;1396419302;153.58;10.30;58.84
						V1;1396419362;153.58;10.31;58.22
						V1;1396419422;1530.58;10.33;58.50
						V1;1396419482;15300.58;10.31;59.49
						V1;1396419542;1300.58;10.35;59.60
						V1;1396419602;1300.58;10.37;59.18
						V1;1396419662;15300.58;10.39;59.54
						V1;1396419722;13300.58;10.39;58.61
						V1;1396419782;1300.58;10.40;58.45
						V1;1396419842;1300.58;10.45;58.81
						V1;1396419902;5300.58;10.46;59.12
						V1;1396419962;13300.58;10.50;58.41
						V1;1396420023;5300.58;10.50;58.53
						V1;1396420082;5300.58;10.49;58.41
						V1;1396420142;53300.58;10.51;58.55
						V1;1396420202;53300.58;10.57;58.64
						V1;1396420262;5300.58;10.65;58.67
						V1;1396420322;53300.58;10.68;58.02
						V1;1396420382;53300.58;10.67;57.74
						V1;1396420442;153300.58;10.66;58.75
						V1;1396420502;15300.58;10.71;58.25
						V1;1396420562;5300.58;10.77;57.93
						V1;1396420622;1300.58;10.78;57.88
						V1;1396420682;3300.58;10.77;57.32
						V1;1396421102;153300.58;11.00;56.01
						V1;1396421162;153300.58;11.01;57.34
						V1;1396421222;3300.58;11.14;57.79
						V1;1396421282;53300.58;11.29;56.74
						V1;1396425842;53300.58;13.95;49.74
						V1;1396425902;153300.58;14.00;50.05
						V1;1396425962;3300.58;14.04;48.78
						V1;1396426022;53300.58;14.00;48.32
						V1;1396426082;5300.58;14.06;49.07
						V1;1396426142;15300.58;14.06;49.30
";
	protected $filename = "2014-04-02.mes";
	protected $stationid = 1;

	/**
	 * @var DataUploader
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new DataUploader;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}
		/**
	 * @covers DataUploader::createDirectory
	 * @todo   Implement testCreateDirectory().
	 */
	public function testCreateDirectory() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
	

	/**
	 * @group Integration
	 * @covers DataUploader::saveToFile
	 * @todo   Implement testSaveToFile().
	 */
	public function testSaveToFile() {
		$filen = $this->object->makePath($this->stationid, $this->filename);
		$filen .= DIRECTORY_SEPARATOR . $this->filename;
		$success = $this->object->saveToFile($this->data, $this->stationid, $this->filename);
		$this->assertTrue($success);
		unlink($filen);
	}

	/**
	 * @group Unit
	 * @covers DataUploader::makePath
	 * @todo   Implement testMakePath().
	 */
	public function testMakePath() {
		$path = $this->object->makePath($this->stationid, $this->filename);
		$this->assertFileExists($path);
	}



}
